-- Creates immutable audit log storage used by /api/audit and writeAuditEvent().
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  request_id text not null,
  actor_id text null,
  actor_email text null,
  actor_role text null,
  action text not null,
  resource text not null,
  resource_id text null,
  outcome text not null default 'success',
  metadata jsonb null,
  before_state jsonb null,
  after_state jsonb null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_audit_logs_created_at_id_desc
  on public.audit_logs (created_at desc, id desc);

create index if not exists idx_audit_logs_actor_email
  on public.audit_logs (actor_email);

create index if not exists idx_audit_logs_action
  on public.audit_logs (action);

alter table public.audit_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'audit_logs'
      and policyname = 'audit_logs_no_direct_client_access'
  ) then
    create policy audit_logs_no_direct_client_access
      on public.audit_logs
      as restrictive
      for all
      to public
      using (false)
      with check (false);
  end if;
end
$$;
